### PR TITLE
UBERTC Tunings + Kernel name change

### PR DESCRIPTION
**Pull request by niclimcy**

### CODE REVIEW

**Comment by niclimcy** [comment]
Don't merge the do not merge commit

**Comment by tarunkapadia93** [comment]
@nick37332001 the optimizations you gave me are too messed up to be frank i will try to get it organized n use only a few which i feel will be needed thanx for the pull anyways :)

**Comment by niclimcy** [comment]
LOL, I refined it a few times... My first version was even more messed up

**Comment by tarunkapadia93** [comment]
here are a few things i thought you goofed up 

https://github.com/tarunkapadia93/android_kernel_xiaomi_msm8916/commit/730508b29ed76a56184b99a56058aaa37f7e3305#diff-b67911656ef5d18c4ae36cb6741b7965R347

y define graphite flags here while you are defining it below separately ??

just use 

CFLAGS_KERNEL   = $(KERNELFLAGS) $(GRAPHITE)

n get it over with 

using graphite is not that easy as you think, if its used you are bound to get a ton of errors n you have to ignore a huge list of file to get around it i cant see any :p 

https://github.com/tarunkapadia93/android_kernel_xiaomi_msm8916/commit/730508b29ed76a56184b99a56058aaa37f7e3305#diff-b67911656ef5d18c4ae36cb6741b7965R385

y use  -Wno-maybe-uninitialized -Wno-array-bounds
you wanna get around the errors about uninitialized warning,  a easy way is to disable the gcc-wrapper and again you have defined diff flags. Just get them all under KERNELFLAGS n use $(KERNELFLAGS) where ever you need 

lastly i dont really know much about Optimization flags but using aggressive flags like -Ofast wont really get you anywhere is its not applied properly infact it will slow down things more 

Peace :)

**Pull request closed without merging**
